name: weather_models
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy>=1.20.0
  - matplotlib>=3.5.0
  - pandas>=1.4.0
  - scipy>=1.8.0
  - jupyter>=1.1.1x
  - scikit-learn>=1.5.2
  - python-dotenv>=1.0.1
  - cartopy>=0.23
  - xarray>=2025.1.1
  - cfgrib>=0.9.15.0